import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../features/customers/data/repositories/customer_statement_repository.dart';
import '../../features/customers/domain/entities/customer_statement_data.dart';
import '../utils/currency_formatter.dart';
import '../utils/date_formatter.dart';

/// Builds a customer-friendly account statement PDF (v1.5.0).
class CustomerStatementPdfBuilder {
  CustomerStatementPdfBuilder._();

  static Future<pw.Document> build(CustomerStatementData data) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => [
          pw.Text(
            'Customer Account Statement',
            style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            data.customerName,
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.Text(
            DateFormatter.format(data.generatedAt),
            style: const pw.TextStyle(fontSize: 10),
          ),
          pw.SizedBox(height: 20),
          _section('Bottle Summary'),
          _row('Business-Owned Bottles Held', '${data.businessOwnedBottlesHeld}'),
          _row('Customer-Owned Bottles Held', '${data.customerOwnedBottlesHeld}'),
          _row(
            'Total Bottles At Customer',
            '${data.totalBottlesAtCustomer}',
            bold: true,
          ),
          pw.SizedBox(height: 16),
          _section('Financial Summary'),
          _row('Outstanding Balance', CurrencyFormatter.format(data.outstandingBalance)),
          _row('Deposit Balance', CurrencyFormatter.format(data.depositBalance)),
          _row('Total Paid', CurrencyFormatter.format(data.totalPaid)),
          pw.SizedBox(height: 16),
          _section('Bottle Issues'),
          _row('Missing Bottles', '${data.missingBottles}'),
          _row('Damaged Bottles', '${data.damagedBottles}'),
          pw.SizedBox(height: 16),
          _section('Recent Deliveries'),
          ..._lines(data.recentDeliveries, emptyLabel: 'No recent deliveries'),
          pw.SizedBox(height: 16),
          _section('Recent Collections'),
          ..._lines(data.recentCollections, emptyLabel: 'No recent collections'),
          pw.SizedBox(height: 16),
          _section('Recent Payments'),
          ..._lines(data.recentPayments, emptyLabel: 'No recent payments'),
          if (data.walkInBusinessBottleSales.isNotEmpty ||
              data.walkInRefills.isNotEmpty ||
              data.walkInExchanges.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            _section('Walk-In History'),
            if (data.walkInBusinessBottleSales.isNotEmpty) ...[
              pw.Text('Business Bottle Sales',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
              ..._lines(data.walkInBusinessBottleSales, emptyLabel: ''),
            ],
            if (data.walkInRefills.isNotEmpty) ...[
              pw.SizedBox(height: 8),
              pw.Text('Customer Refills',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
              ..._lines(data.walkInRefills, emptyLabel: ''),
            ],
            if (data.walkInExchanges.isNotEmpty) ...[
              pw.SizedBox(height: 8),
              pw.Text('Bottle Exchanges',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
              ..._lines(data.walkInExchanges, emptyLabel: ''),
            ],
          ],
          pw.SizedBox(height: 24),
          pw.Divider(),
          pw.SizedBox(height: 8),
          pw.Text(
            'Generated by TubigTrack',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ],
      ),
    );

    return pdf;
  }

  static List<pw.Widget> _lines(
    List<CustomerStatementLine> lines, {
    required String emptyLabel,
  }) {
    if (lines.isEmpty) {
      return [
        pw.Text(emptyLabel, style: const pw.TextStyle(fontSize: 10)),
      ];
    }
    return lines
        .map(
          (l) => pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.SizedBox(
                  width: 80,
                  child: pw.Text(
                    CustomerStatementRepository.formatLineDate(l.date),
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ),
                pw.Expanded(
                  child: pw.Text(
                    '${l.description}${l.detail.isNotEmpty ? ' • ${l.detail}' : ''}',
                    style: const pw.TextStyle(fontSize: 9),
                  ),
                ),
              ],
            ),
          ),
        )
        .toList();
  }

  static pw.Widget _section(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(
        title,
        style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
      ),
    );
  }

  static pw.Widget _row(String label, String value, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 3),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: bold ? pw.FontWeight.bold : null,
            ),
          ),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: bold ? pw.FontWeight.bold : null,
            ),
          ),
        ],
      ),
    );
  }
}
